INSERT INTO `aircraft` (`id`, `name`, `make`, `model`, `manufactured_date`, `serial_no`, `type_certificate`, `total_time`, `total_cycles`, `engine_model`, `engine_serial_no`, `engine_manufactured_year`, `engine_type_certificate`, `engine_total_time`, `engine_time_since_overhaul`, `propeller_model`, `propeller_serial_no`, `propeller_manufactured_year`, `propeller_type_certificate`, `propeller_total_time`, `propeller_time_since_overhaul`, `show_deprecated`, `show_description`, `show_maintenance_reference`, `show_maintenance_instruction`, `show_source`, `summary_date`, `summary_recipients`) VALUES (4, 'SP-FRA', 'Socata', 'Raylle 150 TD', 'XXXX', '2661', 'XXXX', '000:00', NULL, 'Lycoming O-320-D2E', 'XXXX', 'XXXX', 'XXXX', '000:00', '000:00', 'Sensenich XXXX', 'XXXX', 'XXXX', 'XXXX', '000:00', '000:00', b'0', b'1', b'1', b'0', b'1', NULL, NULL);





INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3001, 'Silnik Lycoming O-320-D2E - remont lub wymiana', 'Silnik Lycoming O-320-D2E - remont lub wymiana', 'MAINT', 'E', 'O', NULL, 2000, 144, NULL, NULL, NULL, NULL, NULL, NULL, 'Lycoming SI1009AW', 'Lycoming SI1009AW', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3002, 'Śmigło Sensenich 74DM6-0-58 - remont lub wymiana', 'Śmigło Sensenich 74DM6-0-58 - remont lub wymiana', 'MAINT', 'P', 'O', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Sensenich R17A', 'Sensenich R17A', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3003, 'Iskrowniki Slick serii 4300 – remont lub wymiana', 'Iskrowniki Slick serii 4300 – remont lub wymiana', 'MAINT', 'E', 'O', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Slick SB2-80C', 'Slick SB2-80C', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3004, 'Gaźnik MA-4-5', 'Gaźnik MA-4-5', 'MAINT', 'E', 'O', NULL, 2000, 120, NULL, NULL, NULL, NULL, NULL, NULL, 'Marvel Schebler MSA-3', 'Marvel Schebler MSA-3', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3005, 'Sprawdzenie luzu trzonków zaworów wydechu', 'Sprawdzenie luzu trzonków zaworów wydechu', 'MAINT', 'E', 'I', NULL, 400, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'EASA 2005-0023R3 / SB388C', 'EASA 2005-0023R3 / SB388C', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3006, 'Wymiana śrub mocujących oś koła podwozia przedniego', 'Wymiana śrub mocujących oś koła podwozia przedniego', 'MAINT', 'A', 'R', NULL, 2000, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'EASA 2015-0203', 'EASA 2015-0203', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3007, 'Inspekcja śrub mocujących oś koła podwozia przedniego', 'Inspekcja śrub mocujących oś koła podwozia przedniego', 'MAINT', 'A', 'I', NULL, 200, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'EASA 2015-0203', 'EASA 2015-0203', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3008, 'Sprawdzenie wizualne łoża silnika', 'Sprawdzenie wizualne łoża silnika', 'MAINT', 'E', 'I', NULL, 50, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'GSAC 2001-400 (BS156-71)', 'GSAC 2001-400 (BS156-71)', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3009, 'Sprawdzenie grubości strzemiączka steru wysokości i kierunku', 'Sprawdzenie grubości strzemiączka steru wysokości i kierunku', 'MAINT', 'A', 'I', NULL, 100, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'GSAC 2000-174 (BS155-27) (FAA 2000-20-17)', 'GSAC 2000-174 (BS155-27) (FAA 2000-20-17)', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3010, 'Sprawdzenie struktury płatowca na obecność korozji', 'Sprawdzenie struktury płatowca na obecność korozji', 'MAINT', 'A', 'I', NULL, 100, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'GSAC 82-089', 'GSAC 82-089', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3011, 'Wymiana oleju silnikowego ', 'Wymiana oleju silnikowego ', 'MAINT', 'E', 'R', NULL, 50, 4, NULL, NULL, NULL, NULL, NULL, NULL, 'SB480E', 'SB480E', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3012, 'Kontrola luzów zaworowych ', 'Kontrola luzów zaworowych ', 'MAINT', 'E', 'I', NULL, 400, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SB301B', 'SB301B', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3013, 'Kontrola śrub mocujących misę gaźnika ', 'Kontrola śrub mocujących misę gaźnika ', 'MAINT', 'E', 'I', NULL, 100, 12, NULL, NULL, NULL, NULL, NULL, NULL, 'SB366C', 'SB366C', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3014, 'Regulacja kąta wyprzedzenia zapłonu ', 'Regulacja kąta wyprzedzenia zapłonu ', 'MAINT', 'E', 'I', NULL, 100, 12, NULL, NULL, NULL, NULL, NULL, NULL, 'SB183A', 'SB183A', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3015, 'Kontrola kąta wyprzedzenia zapłonu ', 'Kontrola kąta wyprzedzenia zapłonu ', 'MAINT', 'E', 'I', NULL, 100, 12, NULL, NULL, NULL, NULL, NULL, NULL, 'SB853A', 'SB853A', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3016, 'Sprawdzenie i ustawienie slotów ', 'Sprawdzenie i ustawienie slotów ', 'MAINT', 'A', 'I', NULL, 100, 12, NULL, NULL, NULL, NULL, NULL, NULL, 'BS14-57-01', 'BS14-57-01', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3017, 'Sprawdzenie mocowania statecznika pionowego ', 'Sprawdzenie mocowania statecznika pionowego ', 'MAINT', 'A', 'I', NULL, 100, 12, NULL, NULL, NULL, NULL, NULL, NULL, 'BS40-55-02', 'BS40-55-02', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3018, 'Sprawdzenie podwozia ', 'Sprawdzenie podwozia ', 'MAINT', 'A', 'I', NULL, 50, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'BS42-32-03', 'BS42-32-03', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3019, 'Sprawdzenie ograniczników ruchu owiewki ', 'Sprawdzenie ograniczników ruchu owiewki ', 'MAINT', 'A', 'I', NULL, 100, 12, NULL, NULL, NULL, NULL, NULL, NULL, 'BS75-52-02', 'BS75-52-02', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3020, 'Sprawdzenie występowania luzów nitów wodzika steru wysokości ', 'Sprawdzenie występowania luzów nitów wodzika steru wysokości ', 'MAINT', 'A', 'I', NULL, 100, 12, NULL, NULL, NULL, NULL, NULL, NULL, 'BS85-27-06', 'BS85-27-06', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3021, 'Sprawdzenie mocowania łoża silnika ', 'Sprawdzenie mocowania łoża silnika ', 'MAINT', 'E', 'I', NULL, 100, 12, NULL, NULL, NULL, NULL, NULL, NULL, 'BS86-17-04', 'BS86-17-04', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3022, 'Sprawdzenie przedniego okucia mocowania skrzydeł ', 'Sprawdzenie przedniego okucia mocowania skrzydeł ', 'MAINT', 'A', 'I', NULL, 100, 12, NULL, NULL, NULL, NULL, NULL, NULL, 'BS101-21-01', 'BS101-21-01', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3023, 'Sprawdzenie płatowca na okoliczność występowania korozji ', 'Sprawdzenie płatowca na okoliczność występowania korozji ', 'MAINT', 'A', 'I', NULL, 100, 12, NULL, NULL, NULL, NULL, NULL, NULL, 'BS133-53-03', 'BS133-53-03', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3024, 'Sprawdzenie mocowania amortyzatora przedniego ', 'Sprawdzenie mocowania amortyzatora przedniego ', 'MAINT', 'A', 'I', NULL, 100, 12, NULL, NULL, NULL, NULL, NULL, NULL, 'BS143-32-18', 'BS143-32-18', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3025, 'Sprawdzenie mocowana statecznika poziomego ', 'Sprawdzenie mocowana statecznika poziomego ', 'MAINT', 'A', 'I', NULL, 100, 12, NULL, NULL, NULL, NULL, NULL, NULL, 'BS145-55-10', 'BS145-55-10', b'0');
INSERT INTO `activity` (`id`, `activity_name`, `description`, `activity_type`, `activity_part`, `action_type`, `part_no`, `hours_interval`, `calendar_interval`, `cycles_interval`, `special_interval`, `extention_hours_interval`, `extention_calendar_interval`, `extention_cycles_interval`, `source`, `maintenance_instruction`, `maintenance_instruction_ref`, `deprecated`) VALUES (3026, 'Przegląd iskrowników (wewnętrzny)', 'Przegląd iskrowników (wewnętrzny)', 'MAINT', 'E', 'I', NULL, 500, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'SB2-80C', 'SB2-80C', b'0');
